services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: pip install --no-cache-dir --only-binary :all: -r requirements.txt
    startCommand: gunicorn -w 4 app:app
    pythonVersion: 3.9