"""Added score fields to match table

Revision ID: 5cd25802a667
Revises: 503f9e2dbcc2
Create Date: 2024-06-02 21:38:01.101174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd25802a667'
down_revision = '503f9e2dbcc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_team_a', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('score_team_b', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('score_team_b')
        batch_op.drop_column('score_team_a')

    # ### end Alembic commands ###
